### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by machinaeXlasse** [rynkowsg/hamster-client-android#1]
Hello!

Your tool seems to be exactly what I need to, even better, work with the hamster time tracker.

Yet I have no idea about android development. What steps are necessary to make an .apk file of these source files?

Or is the project not yet usable?

If you still have time to be spend in this project I suggest adding a short section explaining what to do to make it run on android devices. Or even uploading it on [F-Droid](https://f-droid.org/de/tutorials/create-repo/). To me it sounds like a very useful app!

In either case thanks for sharing your code!

**Comment by rynkowsg** [comment]
Sorry, but the project is not production ready and unfortunately its development is no longer active.
Feel free to take it over. I doubt I find time to get back to the project.
